import { useState } from 'react'
import Mes from './Mes'

function Calendario() {
    //interatividade seleção mês
    const [seletor, setSeletor] = useState(0)
    const handleBackButton = ()=>{
        if(seletor === 0){
            setSeletor(11)
        }
        setSeletor(prev=>prev-1)
    }
    const handleForwardButton = ()=>{
        if(seletor === 11){
            setSeletor(0)
        }
        setSeletor(prev=>prev+1)
    }


    const ano = [
        {  
            mes:'janeiro',
            dias:[
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                }
            ]
        },
        {
            mes:'fevereiro',
            dias:[
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                },
                {
                    nome:'',
                    pontos:'',
                    descricao:'',
                    feita:false,
                    comentario:''
                }
            ]
        },
        
    ]
    
    //mapeando o calendario
    const calendario = ano.map((mes,index)=>{
        if(seletor === index){
            return(    
            <div id='calendario' className='flex flex-col items-center justify-center w-full h-full pb-4'>
                <h2 className='w-4/5 flex justify-between text-3xl pb-1 border-b'><span onClick={handleBackButton}>{'<'}</span>{mes.mes}<span onClick={handleForwardButton}>{'>'}</span></h2>
                <div className='flex w-11/12 h-4/5 p-2 mt-4'>
                    <Mes meses={mes}></Mes>
                </div>
            </div>
            )
        }
    })

  return (
    <div className='w-full h-full'>
     {calendario}
    </div>
  )
}

export default Calendario